# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
pairs_freq <- function(Y, C_VEC) {
    .Call(`_plCFA_pairs_freq`, Y, C_VEC)
}

#' @export
get_Lam <- function(A, c_vec, theta) {
    .Call(`_plCFA_get_Lam`, A, c_vec, theta)
}

#' @export
get_Sigma_u <- function(A, theta) {
    .Call(`_plCFA_get_Sigma_u`, A, theta)
}

#' @export
multiThread_completePairwise <- function(Y, C_VEC, A, TAU, LAMBDA, TRANSFORMED_RHOS, FREQ, CORRFLAG, GRFLAG, SILENTFLAG) {
    .Call(`_plCFA_multiThread_completePairwise`, Y, C_VEC, A, TAU, LAMBDA, TRANSFORMED_RHOS, FREQ, CORRFLAG, GRFLAG, SILENTFLAG)
}

#' @export
plCFA <- function(DATA, C_VEC, CONSTRMAT, TAU, LAMBDA, TRANSFORMED_RHOS, CORRFLAG, METHODFLAG, PAIRS_PER_ITERATION = 1L, PROB = .1, ETA = 1e-5, BURN = 200L, MAXT = 1000L, TOLGRAD = 5e-3, TOLPAR = 1e-5, TOLOBJ = 1e-3, TOLCOUNT = 10L, SEED = 123L, SILENTFLAG = 1L) {
    .Call(`_plCFA_plCFA`, DATA, C_VEC, CONSTRMAT, TAU, LAMBDA, TRANSFORMED_RHOS, CORRFLAG, METHODFLAG, PAIRS_PER_ITERATION, PROB, ETA, BURN, MAXT, TOLGRAD, TOLPAR, TOLOBJ, TOLCOUNT, SEED, SILENTFLAG)
}

#' @export
sampling_step <- function(FULL_POOL, METHODFLAG, PROB, PAIRS_PER_ITERATION, N_ITEMS, SEED, SILENTFLAG, ITER) {
    .Call(`_plCFA_sampling_step`, FULL_POOL, METHODFLAG, PROB, PAIRS_PER_ITERATION, N_ITEMS, SEED, SILENTFLAG, ITER)
}

